name: Build and Publish to JFrog

on:
  push:
    branches:
      - main  # Change this as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set Up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install JFrog CLI
        run: |
          curl -fL https://install-cli.jfrog.io | sh
          jf --version

      - name: Configure JFrog CLI
        run: |
          jf c add artifactory-server \
            --url https://trialsbaxgl.jfrog.io/artifactory \
            --user ${{ secrets.ARTIFACTORY_USERNAME }} \
            --password ${{ secrets.ARTIFACTORY_PASSWORD }} \
            --interactive=false
